sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
services:
  - selenium
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm install -g npm@latest
  - npm install -f -g @angular/cli@latest
  - npm install --save-dev @angular/cli@latest
  - npm install
  

before_script:
  - ng build

script: 
- xvfb-run ng test
